DROP TABLE IF EXISTS APP_USER;
CREATE TABLE APP_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  fullName VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL,
  age int NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);